sudo: false
language: node_js
node_js:
  - '4.2.6'

branches:
  only:
    - master

before_script:
  - npm install -g bower
  - bower install

script:
  - gulp build

cache:
  directories:
    - node_modules
    - bower_components
